#whitelist
branches:
    only:
        - master

language: cpp

compiler: gcc

before_install:
        - echo "yes" | sudo apt-add-repository ppa:boost-latest
        - echo "yes" | sudo apt-add-repository ppa:mapnik/boost-backports-1-54
        - echo "yes" | sudo apt-add-repository ppa:h-rayflood/gcc-upper
        - sudo apt-get clean -qq
        - sudo apt-get update -qq
        - sudo apt-get install -qq gcc-4.9 g++-4.9 liblzma-dev libbz2-dev libboost1.54-all-dev
        - export CC="gcc-4.9"
        - export CXX="gcc-4.9"
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50

install:
        - export CXX="g++-4.9"
        - export CC="gcc-4.9"

script:
        - mkdir build
        - cd build
        - cmake ..
        - travis_wait 20 make
          #- travis_wait make install

after_success:
    - cd $TRAVIS_BUILD_DIR
    - ./scripts/push-binary.sh

after_failure:
    - cat $TRAVIS_BUILD_DIR/build/Testing/Temporary/LastTest.log
